title: Matematikk R1
author: René Ask, Edvard Munch Videregående Skole
copyright: "2025"
logo: _logo/r1_logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", README.md, LICENSE.md, LICENSE_CONTENT.md, HOWTOWRITE.md]
description: "Oppgaver til matematikk R1 for læreplanen LK20."

options:
  numbered: true

execute:
  execute_notebooks: off

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath
    - html_image
    - deflist
    - tasklist
    - attrs_inline
    - attrs_block
    - smartquotes
    - colon_fence



repository:
  url: https://github.com/reneaas/matematikk_r1/
  path_to_book: book/
  branch: main/


pdfhtml:
  extra_css:
    - _static/pdf_custom.css
    - _static
  

extra_static_paths:
  - _static

html:
  use_issues_button: false
  use_repository_button: false
  nb_number_source_lines: false
  extra_js:
    - _static
    - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.4/mermaid.min.js
  extra_css:
    - _static/

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_inline_tabs
    - sphinxmermaid
    - sphinxcontrib.tikz
    - sphinx_jupyterbook_latex
    - sphinxcontrib.video
    - munchboka_edutools





  config:
    language: norwegian
    html_favicon: favicon.ico
    html_baseurl: "https://r1.munchboka.no"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3.2/es5/tex-mml-chtml.js
    mathjax3_config:
      loader:
        load: ['[tex]/physics']
      tex:
        packages: {'[+]': ['physics']}
        macros:
          annotateAbove: ["\\mathrel{\\overset{\\substack{\\text{#2} \\\\ \\Bigg\\downarrow}}{#1}}", 2]
          annotateBelow: ["\\mathrel{\\underset{\\substack{\\Bigg\\uparrow \\\\ \\text{#2}}}{#1}}", 2]
          cline: ["\\underline{\\phantom{#1}}", 1]
          and: ["\\quad \\land \\quad"]
          or: ["\\quad \\lor \\quad"]
          liff: ["\\quad \\iff \\quad"]
          limplies: ["\\quad \\implies \\quad"]
          limpliedby: ["\\quad \\impliedby \\quad"]
          lland: ["\\; \\land \\;"]
          degree: ["^\\circ"]
          qog: ["\\quad \\text{og} \\quad"]
          qder: ["\\quad \\text{der} \\quad"]
          qeller: ["\\quad \\text{eller} \\quad"]
          qhvis: ["\\quad \\text{hvis} \\quad"]
          qfor: ["\\quad \\text{for} \\quad"]
          natural: ["\\mathbb{N}"]
          integer: ["\\mathbb{Z}"]
          rational: ["\\mathbb{Q}"]
          real: ["\\mathbb{R}"]
          irrational: ["\\mathbb{Q}^c"]
          qcomma: [",\\quad"]
          nimplies: ["\\quad\\mathrel{\\not\\!\\!\\!\\implies}\\quad"]
          nimpliedby: ["\\quad\\mathrel{\\not\\!\\!\\!\\impliedby}\\quad"]
          niff: ["\\quad\\mathrel{\\not\\!\\!\\!\\iff}\\quad"]
          cubica: ["\\raisebox{-0.4ex}{\\small\\(\\frown\\!\\smile\\)}", 0]
          cubicb: ["\\raisebox{-0.4ex}{\\small\\(\\smile\\!\\frown\\)}", 0]
          t: ["\\mathrm{#1}", 1]
          dot: ["\\vec{#1} \\cdot \\vec{#2}", 2]
          len: ["\\abs{\\vec{#1}}", 1]
          lvec: ["\\overrightarrow{#1}", 1]
          v: ["\\left[#1, #2\\right]", 2]
          proj: ["\\mathrm{proj}_{#1}\\left(#2\\right)", 2]
          mstack: ["\\begin{array}{c}#1\\end{array}", 1]



    html_theme_options:
      pygments_light_style: "github-light"
      pygments_dark_style: "github-dark-high-contrast"
    templates_path:
      - "_templates"
